const DEFAULT_FUNCTION_STATIC_PROPERTIES = ['length', 'prototype', 'name'];
const DEFAULT_FUNCTION_PROTOTYPE_PROPERTIES = ['constructor'];
const DEFAULT_FUNCTION_PROPERTIES = [...DEFAULT_FUNCTION_STATIC_PROPERTIES, ...DEFAULT_FUNCTION_PROTOTYPE_PROPERTIES];

export { DEFAULT_FUNCTION_STATIC_PROPERTIES, DEFAULT_FUNCTION_PROTOTYPE_PROPERTIES, DEFAULT_FUNCTION_PROPERTIES };
